import Header from "../components/Header";
import '/styles/globals.css'
export const metadata = {
  title: "Первая CMS у Uximy",
  description: "Generated by create next app CMS",
  favicon: {
    rel: "icon",
    type: "image/x-icon",
    href: "/static/favicon.ico"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <title>{metadata.title || ''}</title>
        <meta name="description" content={metadata.description} />
        <link rel={metadata.favicon.rel} type={metadata.favicon.type} href={metadata.favicon.href} />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
